### ISSUE TITLE
GPT4: Just A Sweet Kitten

### ISSUE THREAD

**Issue by Xanonymous-GitHub** [steve-jian/github-action-runner-docker#1]
## Description
I would like to suggest a few improvements to enhance security, performance, and readability.
By applying these changes, the Docker image will be more efficient, secure, and easier to maintain.

## Changes
1.    Use the official `debian:bullseye-slim` image for a smaller size and reduced attack surface.
2.    Create and use a dedicated user and group for running the container, instead of running as `root`.
3.    Use the `--no-install-recommends` flag when installing packages to reduce the number of installed packages and overall image size.
4.    Clean up the apt cache and remove unnecessary packages after installation to further reduce the image size.
5.    Change ownership of the `/app` directory and its contents to the dedicated user and group for better security.

## How to implement
```dockerfile
# Use the official debian slim image for smaller size and reduced attack surface
FROM debian:bullseye-slim

# Set working directory
WORKDIR /app

# Use a dedicated user and group for running the container
RUN groupadd -r runner && useradd --no-log-init -r -g runner runner

# Set environment variables
ENV RUNNER_ALLOW_RUNASROOT=false

ARG GHA_RUNNER_TOKEN
ARG GH_JWT_TOKEN
ARG GHA_RUNNER_DOWNLOAD_URL
ARG GH_REPO_URL

COPY --chown=runner:runner ./StartRunner.sh ./

# Install required dependencies and clean up apt cache
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    curl \
    ca-certificates \
    gnupg \
    lsb-release \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null \
    && apt-get remove --purge -y \
    gnupg \
    lsb-release \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg \
    && chmod a+r /usr/share/keyrings/docker-archive-keyring.gpg \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
    docker-ce-cli \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && curl -o actions-runner.tar.gz -L -H "Authorization: Bearer ${GH_JWT_TOKEN}" ${GHA_RUNNER_DOWNLOAD_URL} \
    && tar xzf ./actions-runner.tar.gz && rm ./actions-runner.tar.gz \
    && chown -R runner:runner /app \
    && bash -c ./bin/installdependencies.sh \
    && chmod +x ./StartRunner.sh

# Switch to the dedicated user
USER runner

# Run the script
CMD ["bash","-c","./StartRunner.sh"]
```

**Comment by Xanonymous-GitHub** [comment]
## Docker compose file

```yaml
version: "3.9"

services:
  docker:
    image: docker:dind-rootless
    environment:
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_HOST=unix:///var/run/docker.sock
    tmpfs:
      - /run
      - /tmp
    volumes:
      - certs:/certs/
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "docker", "info"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s

  runner:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GHA_RUNNER_TOKEN=$GHA_RUNNER_TOKEN
        - GH_JWT_TOKEN=$GH_JWT_TOKEN
        - GHA_RUNNER_DOWNLOAD_URL=$GHA_RUNNER_DOWNLOAD_URL
        - GH_REPO_URL=$GH_REPO_URL
    env_file:
      - .env
    environment:
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DOCKER_TLS_VERIFY=0
    volumes:
      - certs:/certs:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - docker
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s

volumes: 
  certs:
```
